apiVersion: v1
kind: Service
metadata:
  name: sentinel
  labels:
    app: sentinel
spec:
  type: ClusterIP
  selector:
    app: sentinel
  ports:
    - name: http
      port: 8930
      targetPort: 8930
      protocol: TCP
